// <auto-generated />
using System;
using MicroserviceBasedFintechApp.Identity.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MicroserviceBasedFintechApp.Identity.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20240620094235_IdentityDatabase")]
    partial class IdentityDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MicroserviceBasedFintechApp.Identity.Core.Entities.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompanyId"));

                    b.Property<Guid>("ApiKey")
                        .HasColumnType("uuid")
                        .HasColumnName("api_key");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<string>("HashedSecret")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hashed_secret");

                    b.Property<DateTime>("RowCreateDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("row_create_date");

                    b.HasKey("CompanyId")
                        .HasName("pk_companies");

                    b.HasIndex("ApiKey", "HashedSecret")
                        .IsUnique()
                        .HasDatabaseName("ix_companies_api_key_hashed_secret");

                    b.ToTable("companies", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
